import { config } from '../config.js';
import type { ContentBrief } from '../types.js';

/**
 * Image agent backend. Defaults to a self-hosted SVG placeholder (served by our
 * own API at /api/image/placeholder) so every post gets a real, instantly
 * loading visual with no API key and no dependency on third-party image hosts.
 * Plug in OpenAI Images or Stability AI by setting IMAGE_PROVIDER (+ key).
 */
export async function generateImage(brief: ContentBrief, prompt: string): Promise<string> {
  if (config.image.provider === 'stability' && config.image.stabilityApiKey) {
    // Stubbed integration point — return placeholder until wired to the API.
    // const res = await fetch('https://api.stability.ai/v2beta/stable-image/generate/core', {...})
  }
  if (config.image.provider === 'openai' && config.llm.openaiApiKey) {
    // Integration point for OpenAI gpt-image-1 / DALL·E.
  }

  // Mock: a branded SVG generated by our own backend (always available).
  const params = new URLSearchParams({
    title: brief.businessType,
    subtitle: prompt || brief.goal,
    badge: brief.platform,
    seed: `${brief.businessType}-${brief.platform}-${prompt}`,
  });
  return `${config.publicBaseUrl}/api/image/placeholder?${params.toString()}`;
}

const FONT =
  "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif";

function escapeXml(s: string): string {
  return s.replace(/[<>&'"]/g, (c) =>
    ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '"': '&quot;' }[c]!),
  );
}

/** Deterministic hue (0-359) from a string. */
function hue(seed: string, offset = 0): number {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) % 360;
  return (h + offset) % 360;
}

/** Wrap text into up to `maxLines` lines of ~`perLine` chars (word-aware). */
function wrap(text: string, perLine: number, maxLines: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = '';
  for (const w of words) {
    if ((line + ' ' + w).trim().length > perLine && line) {
      lines.push(line.trim());
      line = w;
      if (lines.length === maxLines - 1) break;
    } else {
      line = (line + ' ' + w).trim();
    }
  }
  if (line && lines.length < maxLines) lines.push(line.trim());
  return lines.slice(0, maxLines);
}

/**
 * Build a 1024×1024 social-graphic SVG. Deterministic colors from the seed so
 * the same brief always yields the same image.
 */
export function buildPlaceholderSvg(opts: {
  title: string;
  subtitle: string;
  badge: string;
  seed: string;
}): string {
  const h1 = hue(opts.seed);
  const h2 = hue(opts.seed, 40);
  const titleLines = wrap(opts.title || 'Brand', 14, 3);
  const subtitle = escapeXml((opts.subtitle || '').slice(0, 60));
  const badge = escapeXml((opts.badge || '').toUpperCase());

  const titleTspans = titleLines
    .map(
      (ln, i) =>
        `<tspan x="80" dy="${i === 0 ? 0 : 96}">${escapeXml(ln)}</tspan>`,
    )
    .join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024" role="img">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="hsl(${h1},68%,46%)"/>
      <stop offset="1" stop-color="hsl(${h2},72%,28%)"/>
    </linearGradient>
  </defs>
  <rect width="1024" height="1024" fill="url(#bg)"/>
  <circle cx="850" cy="180" r="340" fill="rgba(255,255,255,0.08)"/>
  <circle cx="160" cy="940" r="280" fill="rgba(0,0,0,0.14)"/>
  <g font-family="${FONT}">
    <rect x="80" y="120" rx="22" ry="22" width="${Math.max(160, badge.length * 22 + 60)}" height="60" fill="rgba(255,255,255,0.18)"/>
    <text x="${80 + 30}" y="160" font-size="30" font-weight="700" fill="#ffffff" letter-spacing="2">${badge}</text>
    <text x="80" y="500" font-size="84" font-weight="800" fill="#ffffff">${titleTspans}</text>
    <text x="80" y="${500 + (titleLines.length - 1) * 96 + 90}" font-size="38" font-weight="500" fill="rgba(255,255,255,0.85)">${subtitle}</text>
    <text x="80" y="944" font-size="28" font-weight="600" fill="rgba(255,255,255,0.7)">Autonomous Social Media Agent · AI-generated</text>
  </g>
</svg>`;
}
